name: Generate Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate snake game
    - uses: Platane/snk/svg-only@v3
      with:
            github_user_name: pisal-tejas
            outputs: |
               dist/github-snake.svg
     
